version: "3.9"
services:
  pipelines:
    container_name: dashboard
    build: .
    networks:
      - local
    ports:
      - "3001"
    environment:
      - PORT=3001
  nginx:
    container_name: gitlab-nginx
    image: "nginx:alpine"
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - local
    ports:
      - "3000:80"
    environment:
      - NGINX_PORT=80


networks:
  local:
    driver: bridge